### ISSUE TITLE
Outdated instructions in README. DMFeatureSelector >> selectLastSymbol: not found

### ISSUE THREAD

**Issue by olekscode** [NourDjihan/ClassNameAnalyser#20]
When running this example from README:

```Smalltalk
featureSelector := DMFeatureSelector new.
featureSelector 
  stemming: true;
  filterAllDigits: true; 
  filterSpecialChars: true;
  selectLastSymbol: true.
```

I get an error:

```
Instance of DMFeatureSelector did not understand #selectLastSymbol:
```

I think that README must be updated

**Comment by MoussaSak** [comment]
Outdated instructions in  [README.md](https://github.com/NourDjihan/ClassNameAnalyser/blob/master/README.md)  besides the method mentioned by @olekscode , in third part the ``DMClassNameBlueprintBuilder`` Classe should be renamed to ``DMClassNamesBlueprintBuilder``. Same Thing for ``DMRoassalClassNameBlueprint`` it should be ``DMRoassalClassNamesBlueprint``.

**Comment by NourDjihan** [comment]
Indeed :)
